=== jija-a/EpamTraining/task08xml/src/main/resources/data/publication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/publication"
        xmlns:tns="http://www.example.org/publication" elementFormDefault="qualified">

    <element name="publications">
        <complexType>
            <sequence>
                <element name="publication" type="tns:Publication"
                         minOccurs="1"
                         maxOccurs="16"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Publication">
        <sequence>
            <element name="title" type="string"/>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="JOURNAL"/>
                        <enumeration value="MAGAZINE"/>
                        <enumeration value="BOOKLET"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="monthly" type="boolean"/>
            <element name="Chars" type="tns:Chars"/>
        </sequence>
        <attribute name="id" type="string" use="required"/>
    </complexType>

    <complexType name="Chars">
        <sequence>
            <element name="color" type="boolean"/>
            <element name="page-qty" type="int"/>
            <element name="glance" type="boolean"/>
            <element name="index" type="boolean"/>
        </sequence>
    </complexType>

</schema>

=== jija-a/EpamTraining/task08xml/src/main/resources/data/publication.xml
<?xml version="1.0" encoding="UTF-8"?>
<publications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.example.org/publication"
              xsi:schemaLocation="http://www.example.org/publication publication.xsd">

    <publication id="1">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="2">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="3">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="4">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="5">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="6">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="7">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="8">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="9">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="10">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="11">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="12">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="13">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="14">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="15">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

    <publication id="16">
        <title>Epam-magazine</title>
        <type>MAGAZINE</type>
        <monthly>true</monthly>
        <Chars>
            <color>true</color>
            <page-qty>567</page-qty>
            <glance>false</glance>
            <index>true</index>
        </Chars>
    </publication>

</publications>
