=== jija-a/EpamTraining/task08xml/src/test/resources/papersTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/papersTest"
        xmlns:tns="http://www.example.org/papersTest" elementFormDefault="qualified">

    <element name="paper" type="tns:Paper" abstract="true"/>
    <element name="booklet" type="tns:Booklet" substitutionGroup="tns:paper"/>
    <element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:paper"/>
    <element name="magazine" type="tns:Magazine" substitutionGroup="tns:paper"/>

    <element name="papers">
        <complexType>
            <sequence>
                <element ref="tns:paper"
                         minOccurs="2"
                         maxOccurs="16"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Paper">
        <sequence>
            <element name="title" type="string"/>
            <element name="Chars" type="tns:Chars"/>
        </sequence>
        <attribute name="dateOfIssue" type="date"/>
        <attribute name="genre" type="tns:Genre" default="news"/>
        <attribute name="id" type="long" use="required"/>
    </complexType>

    <simpleType name="Genre">
        <restriction base="string">
            <enumeration value="news"/>
            <enumeration value="sport"/>
            <enumeration value="life"/>
            <enumeration value="tech"/>
            <enumeration value="education"/>
        </restriction>
    </simpleType>

    <complexType name="Chars">
        <sequence>
            <element name="volume" type="positiveInteger"/>
            <element name="is-monthly" type="boolean"/>
            <element name="is-color" type="boolean"/>
            <element name="is-glance" type="boolean"/>
        </sequence>
    </complexType>

    <complexType name="Booklet">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="SubscriptIndex">
        <restriction base="string">
            <pattern value="\d{5,8}"/>
        </restriction>
    </simpleType>

    <complexType name="Newspaper">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                    <element name="subscript-index" type="tns:SubscriptIndex"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Magazine">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                    <element name="subscript-index" type="tns:SubscriptIndex"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

</schema>

=== jija-a/EpamTraining/task08xml/src/test/resources/papersTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/papers"
        xsi:schemaLocation="http://www.example.org/papers papersTest.xsd">

    <newspaper id="1" genre="education">
        <title>Guardian</title>
        <Chars>
            <volume>40</volume>
            <is-monthly>true</is-monthly>
            <is-color>false</is-color>
            <is-glance>false</is-glance>
        </Chars>
        <subscript-index>123412</subscript-index>
    </newspaper>

    <magazine id="2">
        <title>Cars</title>
        <Chars>
            <volume>20</volume>
            <is-monthly>true</is-monthly>
            <is-color>true</is-color>
            <is-glance>false</is-glance>
        </Chars>
        <subscript-index>124332</subscript-index>
    </magazine>

</papers>
